feat: Tag, DrinkCard, icons asset
mash-up-kr/zuzu_web pull request #50
Opened 2022-08-13 09:44 UTC by poiu694

- [x] Button 도 export => export default 로 변경
- [x] styled(Icon)으로 emotion을 적용하려면 props를 내려줘야 하길래 기존 svg 아이콘에도 다 넣고, 새로 넣는 svg 아이콘에도 restProps로 넣었습니다.
- [x] Tag Component 제작 
- [x] DrinkCard 제작

2022-08-13 09:46 UTC, poiu694 commented
tags는 지금 array 형태로 오는지 string 형태로 오는지 몰라서 해당 방식으로 나누어놨고, 기존 데이터에서 category.name 으로 사용하기 위해서 string[] 가 아니라 string으로 받아놓게 임시방편해놨습니다.

2022-08-15 08:34 UTC, poiu694 commented
`Header`, `BottomButton` 도 만들었습니당

2022-08-15 08:35 UTC, poiu694 commented
<img width="200" alt="image" src="https://user-images.githubusercontent.com/43488305/184603317-feb50fe1-1e10-43bb-8164-69faf74f7ee8.png">

2022-08-15 10:20 UTC, huewilliams requested changes
리뷰 늦게 드려서 죄송해요 ㅠㅠ
정말 수고하셨습니다!!!

2022-08-15 10:20 UTC, huewilliams commented on apps/service/src/pages/index.tsx
> +import { ButtonHierarchy } from "design-system/components/Button";
이 부분은 import가 잘못된 걸까요?

2022-08-15 10:20 UTC, huewilliams commented on packages/design-system/assets/svgs/Close.tsx
> +        stroke="#EFEFF8"
Check SVG는 색상 팔레트에서 가져와서 적용하셨는데, Close SVG 색상은 팔레트에 없는 걸까요?

2022-08-15 10:20 UTC, huewilliams commented on packages/design-system/components/Tag.tsx
> +  tags: string[] | string;
tags를 string[]으로만 지정해서 아래에서 Array.isArray 구문으로 분기처리를 하지 않고 (중복되는 로직) 
태그 하나만 전달 할 때 tags=['tag'] 이런 식으로 사용하는 건 어떨까요?

2022-08-15 11:08 UTC, poiu694 commented on packages/design-system/components/Tag.tsx
> +  tags: string[] | string;
[735a68b](https://github.com/mash-up-kr/proof_web/pull/50/commits/735a68b8852ff9ae2b0c4cbc1ef10f9b8e2906f0) 이런식으로 얘기해주신게 맞을까요?

2022-08-15 11:08 UTC, poiu694 commented on packages/design-system/assets/svgs/Close.tsx
> +        stroke="#EFEFF8"
[9a63454](https://github.com/mash-up-kr/proof_web/pull/50/commits/9a63454ae0a534833f181ca3627caf2cf878190e) 반영했습니다!

2022-08-15 11:08 UTC, poiu694 commented on apps/service/src/pages/index.tsx
> +import { ButtonHierarchy } from "design-system/components/Button";
이거는 컨벤션을 조금 정해도 될 것 같긴 한데, [735a68b](https://github.com/mash-up-kr/proof_web/pull/50/commits/735a68b8852ff9ae2b0c4cbc1ef10f9b8e2906f0) 이런식으로 design-system에서 전부 가져올 수 있게 만들면 될까요?

2022-08-15 11:19 UTC, huewilliams commented on apps/service/src/pages/index.tsx
> +import { ButtonHierarchy } from "design-system/components/Button";
넵 그러면 될 것 같습니다!

2022-08-15 11:20 UTC, huewilliams commented on packages/design-system/assets/svgs/Close.tsx
> +        stroke="#EFEFF8"
🤩🤩

2022-08-15 11:20 UTC, huewilliams commented on packages/design-system/components/Tag.tsx
> +  tags: string[] | string;
넵!! 리뷰 모두 반영해주셔서 감사합니당

2022-08-15 11:21 UTC, huewilliams approved these changes
수고 하셨습니다!! 해커톤까지 같이 달려요 ㅋㅋㅋ

2022-08-15 11:22 UTC, otterji approved these changes
상민... 채고야... 🥺👍🏻

2022-08-15 11:22 UTC, otterji commented on apps/service/src/pages/worldcup.tsx
> +    const nextIsActive = [...isActive];
마이너한거긴 하지만,, boolean 타입을 가진 변수명이 다 is~~ 니,  isNextActive 같은걸로 통일하면 어떨까욤?

2022-08-15 11:46 UTC, poiu694 commented on apps/service/src/pages/worldcup.tsx
> +    const nextIsActive = [...isActive];
`isActive` 를 업데이트 하기 위해서 `다음에 사용할 isActive` 의미로 사용하려구 `nextIsActive` 라고 명명했었는데

`isNextActive` 는 nextActive라는 변수가 있는지 여부를 확인하는 변수로 사용할 것 같다는 생각을 할 수 있을 것 같아요! 어떻게 생각하시나요 ?!

2022-08-15 11:57 UTC, merged

2022-08-15 15:04 UTC, otterji commented on apps/service/src/pages/worldcup.tsx
> +    const nextIsActive = [...isActive];
아하 그런 의미면 이렇게 사용하는게 맞는 것 같아요! 제가 헷갈렸네용 🥹

2022-08-15 15:10 UTC, zi-gae commented on apps/service/src/pages/worldcup.tsx
> +    const nextIsActive = [...isActive];
배열이면 변수명 복수로 지어주면 더 좋을 것 같아유 🙇🏻‍♂️