Feature/round
mash-up-kr/zuzu_web pull request #52
Opened 2022-08-15 15:22 UTC by poiu694

<img width="200" alt="image" src="https://user-images.githubusercontent.com/43488305/184664096-bdce0d4d-252a-44b9-a854-7190c3ff763b.png">

Round 선택 페이지 간단하게 만들었습니당!

2022-08-16 16:14 UTC, huewilliams requested changes
작업 수고하셨습니당! 👏👏👏

2022-08-16 16:14 UTC, huewilliams commented on apps/service/src/components/Header.tsx
> +  left: 5.7%;
이 부분은 %로 지정해주신 이유가 있을까요?
RoundCard의 RightIcon에서는 고정 px로 작업되어 있어서 단위를 통일하면 좋을 것 같습니다.

2022-08-16 16:14 UTC, huewilliams commented on apps/service/src/pages/round.tsx
> +type Round = {
RoundCard에 있는 Round Interface를 쓰지 않고 다시 Round Type을 만들어서 사용하신 이유가 있을까요?

2022-08-16 16:14 UTC, huewilliams commented on apps/service/src/pages/round.tsx
> +    new Array(dummyRound.length).map(() => false)
같은 동작이지만 .fill(false)를 쓰는 것이 좋아보입니다!

2022-08-16 16:14 UTC, huewilliams commented on apps/service/src/pages/round.tsx
> +    const $li = $ul.closest("li");
물론 함수를 하나로 관리한다는 이점이 있지만
저는 dom 관련 로직을 직접 다뤄야 한다는 것이 조금 리스크라고 생각해서(li에서 id를 넣어줘야 한다거나, dom 조작을 해야함).
각 li에 onClick handler를 전달하는 방식을 선호하는데, 어떻게 생각하시나요?

2022-08-17 10:13 UTC, poiu694 commented on apps/service/src/components/RoundCard.tsx
> +  border-radius: 50%;
<img width="287" alt="image" src="https://user-images.githubusercontent.com/43488305/185094201-aff533f0-d1b3-4345-8e3e-1f60df20bda0.png">

선택이 되어있는 상황에서, 칵테일 아이콘이 동그라미 이미지로 보이기 위해서 넣어두었습니다!

2022-08-17 10:25 UTC, poiu694 commented on apps/service/src/pages/round.tsx
> +    const $li = $ul.closest("li");
저는 이벤트 위임 관점에서 ul에 이벤트를 처리한다는 점이 막상 좋다고만 생각해봤는데,

해당 케이스에서는 이벤트 위임을 한다고 성능이 눈에 띄게 변할 것 같지도 않아서 고민이 좀 되긴 하네요!

2022-08-17 10:31 UTC, poiu694 commented on apps/service/src/pages/round.tsx
> +type Round = {
d엥..? [1679a16](https://github.com/mash-up-kr/proof_web/pull/52/commits/1679a1609d1e02312f740fc01e12ac05a81d6dab) 반영했습니다!

2022-08-17 10:31 UTC, poiu694 commented on apps/service/src/pages/round.tsx
> +    new Array(dummyRound.length).map(() => false)
[608cd6e](https://github.com/mash-up-kr/proof_web/pull/52/commits/608cd6e834c87b7dc5b12666e328f3f4ed424c85) :+1:

2022-08-17 13:03 UTC, huewilliams commented on apps/service/src/components/RoundCard.tsx
> +  border-radius: 50%;
아하 이해했습니다!

2022-08-17 13:05 UTC, huewilliams approved these changes

2022-08-17 13:46 UTC, otterji approved these changes
오와 고생하셨습니당 🥹

2022-08-17 16:45 UTC, otterji commented on apps/service/src/components/RoundCard.tsx
> +interface RoundCardProps extends React.HTMLAttributes<HTMLLIElement> {
`HTMLAttributes<HTMLLIElement>` 대신 `ComponentProps<'li'>` 를 쓰는건 어떨까요 ?

[HTMLAttributes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L1843)는 전달받은 제네릭을 내부적으로 활용을 안하더라구요!
HTML 요소가 받을 수 있는 공통의 어트리뷰트만 받고, 제네릭에 맞는 세부적인 속성들까지는 추론이 안되는 걸로 알고 있습니다.

아래의 사진처럼 HTMLAttributes를 쓰면 [value](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#attr-value)라는 속성이 추론이 안되더라구요!
이 외에도 다양한 방법이 있으니 같이 의논해보고, 하나로 정해서 일관성 있게 가져가는 것도 좋을 것 같습니다!

<img width="485" alt="image" src="https://user-images.githubusercontent.com/52898735/185193475-678a54d4-920b-46a0-81cb-6257249b0133.png">

2022-08-18 03:35 UTC, poiu694 commented on apps/service/src/components/RoundCard.tsx
> +interface RoundCardProps extends React.HTMLAttributes<HTMLLIElement> {
되게 좋은 것 같아요! 시간나면 일괄적으로 변경해놓겠습니다!

2022-08-19 08:23 UTC, poiu694 commented on apps/service/src/components/Header.tsx
> +  left: 5.7%;
[36ca519](https://github.com/mash-up-kr/proof_web/pull/52/commits/36ca519b5641771287eb45be0dc75fb7d631725d) 반영이제야 완료.>~!

2022-08-19 08:23 UTC, poiu694 commented on apps/service/src/pages/round.tsx
> +    const $li = $ul.closest("li");
[5477dc4](https://github.com/mash-up-kr/proof_web/pull/52/commits/5477dc485dd5b72ea704dbb07ee21855bc7e619c) 방식으로 바꾸었습니당!

2022-08-19 08:23 UTC, poiu694 commented on apps/service/src/components/RoundCard.tsx
> +interface RoundCardProps extends React.HTMLAttributes<HTMLLIElement> {
[9ef2a4](https://github.com/mash-up-kr/proof_web/pull/52/commits/9ef2a4799c488091078a281488b0cb54a7b58f34) 변경!

2022-08-19 08:24 UTC, poiu694 commented
수요일 회의하면서 나왔던 말줄임표랑, tag가 많을 시 +n 으로 나오게 바꾸었습니당!

2022-08-19 08:24 UTC, merged

2022-08-19 08:35 UTC, otterji commented
오 이거 내가 방금 작업하면서 했는뎅 🤣
상민님 작업하신 내용 보고 반영해 이따 한번에 피알 올리겠습니당~~~ 고생하셨습니당 👏🏻👏🏻

2022-08-19 11:23 UTC, poiu694 commented
> _오 이거 내가 방금 작업하면서 했는뎅 🤣
상민님 작업하신 내용 보고 반영해 이따 한번에 피알 올리겠습니당~~~ 고생하셨습니당 👏🏻👏🏻_

으악...! ㅠㅠㅠㅠ 미리 말 드릴걸 죄송하빈다