feat: useWorldCup,  recoil worldcup state
mash-up-kr/zuzu_web pull request #61
Opened 2022-08-21 08:42 UTC by poiu694

## 작업사항

- [x] Drink interface 임시 변경 (스웨거, 노션 등 불일치 등으로 임시 방편 사용)
- [x] 프론트에서 사용하는 `DrinkWithRound` 제작
- [x] `useWorldCup` 훅 작성 및 필요한 유틸 제작
- [x] DrinkImage는 background: cover => contain으로 해서 이미지 일부분만 보이던 것을 바꾸었습니다
- [x] 페이지별 선택에 따라 리코일에 상태 넣기

## 전달사항

- Drink interface를 백엔드에서 오는 방향으로 수정해야 할 것 같아요!
- 월드컵..ㅇ잘되는거같은데... 안되는 부분 있으면 말씀해주세요......

## 궁금사항

- result 는 param으로 어떤 주류인지 확인하는 방향으로 바꾸기로 했는데, 라운드, 월드컵 페이지에서 새로고침 되는 경우 등을 고려해야 할 것 같아요!
  + 지금 생각하는건 recoil 상태 기본적인 초기값을 논의 후 설정하는게 제일 편할 것 같은데, 다른 좋은 방법이 있을까요?

2022-08-23 11:56 UTC, otterji commented
월드컵 아주 잘 됩니다요!! 고생하셨습니당

> result 는 param으로 어떤 주류인지 확인하는 방향으로 바꾸기로 했는데, 라운드, 월드컵 페이지에서 새로고침 되는 경우 등을 고려해야 할 것 같아요!
지금 생각하는건 recoil 상태 기본적인 초기값을 논의 후 설정하는게 제일 편할 것 같은데, 다른 좋은 방법이 있을까요?

위에서 말씀하신 내용이 라운드, 월드컵 페이지에서 새로고침 했을때 각각 어떻게 처리할지에 관해 말씀하신걸까요??

2022-08-23 12:05 UTC, otterji approved these changes

2022-08-23 13:15 UTC, poiu694 commented
@otterji 넹 맞습니다! 정확히는 모든 페이지에서 새로고침시 막아야 할 것 같아요..!

2022-08-24 03:47 UTC, poiu694 commented
[0cf193c](https://github.com/mash-up-kr/proof_web/pull/61/commits/0cf193c24ab49ea4ed08cf882865fa79c626977d) 타이틀 컴포넌트에서 현재 문제점이 백엔드에서는 한 줄로 주는데 그거를 짜르기가 어려워서 한 줄 + 개행문자 인식으로 바꾸었습니다!

근데, 백엔드에서는 월드컵 타이틀 정보가 안드에서도 쓰고 있어서, 개행문자를 넣어주기가 어렵다구 하네요... ㅠㅅㅜ

2022-08-24 16:08 UTC, huewilliams requested changes
코드량이 많고 복잡한 로직도 있었는데, 정말 수고 많으셨습니다!!
JSDoc 작성해주셔서 코드 분석하는데 편해서 좋았습니다.

여행 잘 다녀오세요 ~ !

2022-08-24 16:08 UTC, huewilliams commented on apps/service/src/pages/worldcup.tsx
> +    // 2인 경우는 월드컵 결과 페이지에서 뒤돌아갔을 때 임시 방편으로 업데이트 되는 것 막아놓기
2일 때는 왜 막아두신 건가요?

2022-08-24 16:08 UTC, huewilliams commented on apps/service/src/pages/worldcup.tsx
> +        ></TitleWrapper>
닫는 태그 합쳐주시죵

2022-08-24 16:10 UTC, poiu694 commented on apps/service/src/pages/category/[with].tsx
> +        title: "이 술을 마시는건\n 어떤 상황인가요?",
감사합니당!

2022-08-24 16:12 UTC, poiu694 commented on apps/service/src/components/DrinkCard.tsx
> +          {drink?.category}
현재 렌더링적으로 아쉬운 부분이

월드컵 "결승"(2강)라운드에서 우승 주류를 선택하고 난 후에, 바로 결과페이지로 가는게 아니라

아무것도 하지 않는 1강 라운드를 잠시 들리는 형태로 지금 렌더링이 되고 있어서 이때 옵셔널로 안주면 문제가 생기더라고요..!

2022-08-24 16:13 UTC, poiu694 commented on apps/service/src/components/DrinkCard.tsx
> +          {drink?.category}
그래서 임시 방편으로 옵셔널을 주긴 했습니다! ㅠㅠ 나중에 리팩토링할 때 수정할까 했다가 이걸 공유 안했네요...ㅠㅠㅠ

2022-08-24 16:14 UTC, huewilliams commented on apps/service/src/components/DrinkCard.tsx
> +          {drink?.category}
음 뭔가 2강일 때만 예외처리를 해줘야 할 것 같네요

2022-08-24 16:16 UTC, poiu694 commented on apps/service/src/pages/category/index.tsx
> +import { WithWhoType, worldCupState } from "../../store";
앗........

2022-08-24 16:16 UTC, otterji approved these changes

2022-08-24 16:16 UTC, otterji commented on apps/service/src/pages/worldcup.tsx
> +        ></TitleWrapper>
```suggestion
        <TitleWrapper
          title={"비 오는 날씨엔 어떤 술이 더 끌리나요?"}
          textAlign="center"
        />
```
편하게 써제션 달아드릴게요 ㅎ
`<TitleWrapper />` 랑 `<Title />` 사용하는 부분 통일성 있게 가져가면 좋을 것 같은데 제가 작업할때 같이 반영해보겠습니당~!

2022-08-24 16:17 UTC, huewilliams commented on apps/service/src/pages/worldcup.tsx
> +        ></TitleWrapper>
suggestion은 안 써봤는데 좋은 기능이군요

2022-08-24 16:17 UTC, poiu694 commented on apps/service/src/utils/helperArray.ts
> +  while (index--) {
제가 원했던 로직은 마지막 인덱스부터 predicate 를 처음 만족하는 인덱스를 반환하는 함수를 사용하고 싶었습니당!

findIndex 를 이용하는 방법으로 처음에 생각했는데, 해당 함수는 마지막 인덱스가 아니라 첫 인덱스를 반환 하고, 더이상 순회하지 않는 것으로 알고있어서 원하는 대로 하기 위해서는 바꾸어 써야 하는 것으로 알고있습니다!

그래서 해당 findIndex를 이용하려면 reverse 후에 findIndex를 했어야 하는데 그러면 현재 구현한 방식보다 오버헤드가 조금 있어보여서 지금 방식으로 생각했습니다!

2022-08-24 16:18 UTC, otterji commented on apps/service/src/pages/worldcup.tsx
> +        ></TitleWrapper>
@huewilliams 신우 겁나 많이 쓰게될듯 ㅋ ㅋ 써제션러

2022-08-24 16:18 UTC, poiu694 commented on apps/service/src/pages/worldcup.tsx
> +        ></TitleWrapper>
너무좋다.....감사합니다!

2022-08-24 16:20 UTC, poiu694 commented on apps/service/src/pages/worldcup.tsx
> +        ></TitleWrapper>
[83dec1a](https://github.com/mash-up-kr/proof_web/pull/61/commits/83dec1a2edca3cd0cecd012c2a0cefd3eb1d23d3) 반영했습니다!

2022-08-24 16:21 UTC, huewilliams commented on apps/service/src/utils/helperArray.ts
> +  while (index--) {
아하 성능적으로 지금 구조가 더 좋아보이네요 좋습니당

2022-08-24 16:28 UTC, poiu694 commented on apps/service/src/pages/result.tsx
> +    setWinnerDrink(winnerDrink!);
[5f421ce](https://github.com/mash-up-kr/proof_web/pull/61/commits/5f421cea00c83b8eb70d0e0f48fcb40c8b5884ba) 반영했습니다~!!@

2022-08-24 16:32 UTC, poiu694 commented on apps/service/src/pages/category/index.tsx
> +      with: withWho as WithWhoType,
[b7b5027](https://github.com/mash-up-kr/proof_web/pull/61/commits/b7b5027c5b887fb723862d37a2d31dd92958b345) 타입 가져왔습니다..! 아까 급하게 올린다고 푸시가 꼬여서 타입이 말썽이네요 ㅠㅠㅜㅜ

2022-08-24 16:32 UTC, poiu694 commented on apps/service/src/store/worldcup.ts
> +export const worldCupState = selector<WorldCup>({
[b7b5027](https://github.com/mash-up-kr/proof_web/pull/61/commits/b7b5027c5b887fb723862d37a2d31dd92958b345) WIthWhoType 가져오면서 반영했습니다!

2022-08-24 16:35 UTC, poiu694 commented on apps/service/src/store/worldcup.ts
> +    with: "alone",
[3024031](https://github.com/mash-up-kr/proof_web/pull/61/commits/3024031363ac94099dcb95911300689706ba37bf) null 추가 및 초기값 설정 했습니당!

2022-08-24 16:35 UTC, poiu694 commented on apps/service/src/store/worldcup.ts
> +    with: "alone",
일단 사용하는 부분이 지금으로서는 없어서 분기처리는 로직을 짜다보면 하게 될 것 같아요!

2022-08-24 16:37 UTC, poiu694 commented on apps/service/src/pages/category/index.tsx
> +    href: "/category/SOLO",
[b7b5027](https://github.com/mash-up-kr/proof_web/pull/61/commits/b7b5027c5b887fb723862d37a2d31dd92958b345) 여기도 마찬가지로 타입 가져와서 해결했습니당!

2022-08-24 16:41 UTC, poiu694 commented on packages/design-system/components/Title.tsx
> +          dangerouslySetInnerHTML={{ __html: title }}
아까 로직 확인할 때 지금처럼 안적으면 안되길래 넣었었는데... 지금 다시 확인해보니까 잘 되네요!

[25d092f](https://github.com/mash-up-kr/proof_web/pull/61/commits/25d092fc0be8745919cce98e3c9c37002302eacb) 삭제했습니다!

2022-08-24 16:43 UTC, poiu694 commented on apps/service/src/pages/category/[with].tsx
>    cards: {
해당 부분은 react-query를 쓰면서 cards로 받아오는게 아니라 withWho로 받게 될 것 같습니다!

react-query 피알에 삭제하면서 반영하겠습니다!

2022-08-24 16:45 UTC, huewilliams approved these changes
빠른 반영 최고에요
빠른 Approve 하겠습니다

2022-08-24 16:48 UTC, poiu694 commented on apps/service/src/components/ContentCard.tsx
> +const ContentCard = ({ title, description, ...restProps }: Props) => {
[ec320d8](https://github.com/mash-up-kr/proof_web/pull/61/commits/ec320d8b0dded75f28f8fd2d055917da9271e3b0) 끝....

2022-08-24 16:50 UTC, merged